# Generated by Django 2.0.4 on 2018-04-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('defaultThumbnail', models.URLField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('channelId', models.CharField(max_length=30)),
                ('channelTitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('ytId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('commentCount', models.IntegerField()),
                ('viewCount', models.IntegerField()),
                ('dislikeCount', models.IntegerField()),
                ('likeCount', models.IntegerField()),
            ],
        ),
    ]
